---
title: "Ecoregion Report"
author: "Deepa Filatow"
date: "May 25, 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ecosection of British Columbia

Below is a map of the ecosections coloured by ecosection code.

```{r loadlibraries, include = FALSE, message= FALSE}
library (bcdata)
library (sf)
library (raster)
library (fasterize)
library (leaflet)
library (shiny)

#load data
alb = 3005
ecosections <- bcdc_get_data ("ccc01f43-860d-4583-8ba4-e72d8379441e", crs = alb)
elev <- raster("C:/Users/dfilatow/Documents/GISdownloads/HABC/elev.tif")
```


```{r ecosectionmap}
plot(ecosections["ECOSECTION_CODE"])
```

### Ecosection Selection

This part is not working

```{r ecoselect, echo = FALSE}
selectInput("es_input", "Ecosection Selection", as.list(ecosections$ECOSECTION_NAME))
renderText(paste("You have chosen", input$es_input))
renderLeaflet (filter(ecosections, ECOSECTION_NAME == as.character(input$es_input)))
es.name <- renderText(input$es_input)
```



### Ecosection Topography

Here is a map of the `r input$es_input` Ecosection showing the 1 ha mean elevation.

```{r elevecosection}

es <- filter(ecosections, ECOSECTION_NAME == as.character(input$es_input))
es.elev <- elev %>% raster::crop(es) %>% mask(es)
plot(es.elev)

```