---
title: "Ecoregion Report"
author: "Deepa Filatow"
date: "May 25, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ecosection of British Columbia

Below is a map of the ecosections coloured by ecosection code.

```{r, include=FALSE}
library (bcdata)
library (sf)
library (raster)
library(fasterize)
alb = 3005
ecosections <- bcdc_get_data("ccc01f43-860d-4583-8ba4-e72d8379441e", crs = alb)
elev <- raster("C:/Users/dfilatow/Documents/GISdownloads/HABC/elev.tif")
plot (ecosections["ECOSECTION_CODE"])
```

```{r, include=FALSE}

#ecosections$ELEV_MAX <- raster::extract(elev, ecosections, fun = max)
#plot (ecosections["ELEV_MAX"])
#es.r <- fasterize(ecosections, elev,field = "OBJECTID")
#test <- zonal(elev, es.r)
#plot(test)

```
Here is a map of the Elk Valley Ecosection showing the 1 ha mean elevation.

```{r ecosections}
#print(ecosections$ECOSECTION_NAME)
es <- filter(ecosections, ECOSECTION_NAME == "Elk Valley")
es.elev <- elev %>% raster::crop(es) %>% mask(es)
plot(es.elev)

```

This is a histogram of the 1 ha elevation in the ecosection.

```{r}
hist(es.elev)
```

